prusa3d/Prusa-Error-Codes

- .gitignore
- .gitlab-ci.yml
- prusaerrors/shared/codes.py
- prusaerrors/sl1/codes.py
- setup.py
- tests/test_exports.py
- tests/test_sl1.py
This allows for easier installation.
> Wrap everything except tests in prusaerrors package

- prusaerrors/sl1/codes.py
- strings are extracted in sl1fw (does not have their own translation files)
> sl1: add gettext support

- prusaerrors/sl1/codes.py
Add SL1 wizard error codes. MOre wizard codes ar going to come once
uvcalibration is included.
> SL1: add wizard error codes

- prusaerrors/sl1/codes.py
- remote_install.sh
- setup.py
- new warnings (PERPARTES_NOAVAIL_WARNING, MASK_NOAVAIL_WARNING, OBJECT_TRUNCATED_WARNING)
- new error (PRELOAD_FAILED)
- fix: remote_install.sh
- version bump
> SL1: The part of the project and related stuff refactoring

- 10_SL1/errors.yaml
- New codes to cover all errors in a64-fw
- Formatting fixes
- Texts for all codes. There are no "None" texts
> Sl1 errors to error codes

- prusaerrors/shared/codes.py
fix: ErrorCode title is missing return value
> fix: missing title value

- 10_SL1/errors.yaml
- single project exception into many of them
- better warning handling
> Project errors and warnings

- 10_SL1/errors.yaml
Fixes missing type specifier.
Part of SL1SW-1260
> Fix variable placeholder

- 10_SL1/errors.yaml
> Remove unneeded emoticon.

- 10_SL1/errors.yaml
for the new SLA tank surface cleaning wizard
> add GARBAGE_COLLECTOR_MISSING error

- 10_SL1/errors.yaml
> SLA: TILT_MOVE_FAILED(10104): add

- 04_MMU/button_operations.h
- 04_MMU/error-codes.yaml
- 04_MMU/errors_list.h
Add 4106 FSENSOR TOO EARLY
cleared some older comments
> Update MMU error-codes.yaml

- 04_MMU/error-codes.yaml
add FINDA FLICKERS / INSPECT FINDA error state
> add FINDA FLICKERS error

- 12_MINI/error-codes.yaml
BFW-3113
Add bootloader errors to error yaml.
> Add all bootloader errors.

- 04_MMU/error-codes.yaml
- generate_buddy_headers.py
> A generator for Buddy FW headers and some MMU fixes

- 04_MMU/error-codes.yaml
for MMU MCU 5V VCC underpower detection
> Add 04306 MMU MCU UNDERPOWER error

- 04_MMU/error-codes.yaml
- MMU not responding/Communication error: add DisableMMU
- MMU FW update needed: add ResetMMU
PFW-1485
PFW-1486
> Add ResetMMU and DisableMMU buttons to specific error screens

- 04_MMU/error-codes.yaml
Counter part of https://github.com/prusa3d/Prusa-Firmware/pull/4073
> Rename `MMU unit` to `MMU`

- 12_MINI/error-codes.yaml
- 13_MK4/error-codes.yaml
- 17_XL/error-codes.yaml
- README.md
Add new MINI errors for better customer support.
Add MK4 & XL errors.
> Migrate MK4 & XL error yamls

- 20_MK35/error-codes.yaml
Derived from MK4, some of the error codes will be removed and replaced with other ones due to different extruder assembly.
> Introduce MK3.5 error codes

- 17_XL/error-codes.yaml
> xl: Add dwarf nozzle overcurrent error code

- 13_MK4/error-codes.yaml
- 16_iX/error-codes.yaml
- 17_XL/error-codes.yaml
- 20_MK3.5/error-codes.yaml
[BFW-4636](https://dev.prusa3d.com/browse/BFW-4636)
> Shorten power painic detected on startup, it didn't fit on the screen before.

- 13_MK4/error-codes.yaml
- 20_MK3.5/error-codes.yaml
> Add title to XX701

- generate_buddy_headers.py
> Fix includes in header generation

- 13_MK4/error-codes.yaml
- 20_MK3.5/error-codes.yaml
BFW-4965
+ Remove irrelevant errors from MK3.5 yaml.
+ Shorten Firmware Update Required text on MK3.5
> Edit MK3.5 errors

- 13_MK4/error-codes.yaml
- 20_MK3.5/error-codes.yaml
> Final text of MK3.5 & MK4 & MK3.9 wrong FW error

- 23_MK3.5/error-codes.yaml
- README.md
BFW-4968
Change MK3.5's USB_PID from 20 to 23
> Change MK3.5 USB PID

- yaml/buddy-error-codes.yaml
> Add XL Enclosure's error codes

- yaml/buddy-error-codes.yaml
This is the first notice error code, using section 7 for now.
BFW-4858
> Add notice error code for Cold Pull

- yaml/buddy-error-codes.yaml
> Enable cold-pull messages on XL

- 10_SL1/errors.yaml
- prusaerrors/shared/codes.py
SLA dropped support for API key authorization.
Part of: SL1SW-2110
> sl1: add code 10408 INVALID_PASSWORD

- yaml/buddy-error-codes.yaml
> Add gcode cropped error code

- yaml/buddy-error-codes.yaml
@lukash forgot to push to this repo and made the change only locally in the BFW (commit 115409de1ca298dbff968c45510e6b8933cb8b8a)
BFW-4750
> Allow PRECISE_REFINEMENT_FAILED for iX

- yaml/buddy-error-codes.yaml
> Add XX_MCU_MAX_TEMP_AMB error codes

- yaml/buddy-error-codes.yaml
Update BUDDY_XXX_MAX_TEMP texts per the product team request.
Remove BUDDY_XXX_MAX_TEMP_AMB error codes which turned out to be never used.
BFW-5741
> Update BUDDY_XXX_MAX_TEMP texts

- yaml/buddy-error-codes.yaml
> Document "printers" field

- README.md
> Add new printers' product ID's into README

- yaml/buddy-error-codes.yaml
> Add error code for iX on filament load timeout

- yaml/buddy-error-codes.yaml
> Add steel sheet not detected error

- yaml/buddy-error-codes.yaml
> Fix a typo in STEEL_SHEET_NOT_DETECTED

- include/button_operations.h
- prusaerrors/shared/codes.py
- tests/test_connect.py
- yaml/buddy-error-codes.yaml
> Add Core ONE support

- yaml/buddy-error-codes.yaml
> Add Warning USB_DRIVE_FAT32_NOT_PRESENT

- yaml/buddy-error-codes.yaml
> Correct Warning USB_DRIVE_UNSUPPORTED_FILE_SYSTEM

- yaml/buddy-error-codes.yaml
> Change heater timout to 10 mins for iX

- yaml/buddy-error-codes.yaml
> Add CHAMBER_FAILED_TO_REACH_TEMP

- yaml/buddy-error-codes.yaml
> Add UNEVEN_BED_ALIGN_PROMPT

- yaml/buddy-error-codes.yaml
> BFW-6242_chamber_temperature_warnings

- yaml/buddy-error-codes.yaml
> chmaber to chamber typo correction to

- yaml/buddy-error-codes.yaml
Add atribute gui_layout to errors/warnings with known statically defined layouts.
> Add attribute gui_layout for unit testing

- yaml/buddy-error-codes.yaml
> Add chamber vents warnings

- yaml/buddy-error-codes.yaml
- Remove XL from open/close ventilation grills
- Remove PRINT_PREVIEW from errors that are used outside print preview as well
> Minor edits

- yaml/buddy-error-codes.yaml
> Add chamber maxtemp and mintemp errors

- yaml/buddy-error-codes.yaml
> Add XL to chamber temp errors

- yaml/buddy-error-codes.yaml
> Add error codes for filament sensor troubleshooting

- yaml/buddy-error-codes.yaml
> Add chamber fan errors

- README.md
- generate_buddy_headers.py
- tests/test_verify_buddy_errors_content.py
- yaml/buddy-error-codes.yaml
> Remove unused errors from error yaml

- yaml/buddy-error-codes.yaml
> Add HEPA filter warnings for C1

- yaml/buddy-error-codes.yaml
> Approve XX701 + XX831 + XX832

- yaml/buddy-error-codes.yaml
[BFW-6431](https://dev.prusa3d.com/browse/BFW-6431)
> Add heatbreak temperature runaway errcode on iX

- yaml/buddy-error-codes.yaml
[BFW-6431](https://dev.prusa3d.com/browse/BFW-6431)
> Rename heatbreak runaway -> heatbreak cooling too slow

- generate_buddy_headers.py
BFW-7173
Neglect printer ID and list out errors for all printers at once - used for translations
> Add ignore_printer_id option to generate_buddy_headers.py script

- yaml/buddy-error-codes.yaml
> Add ACTION_SELFTEST_REQUIRED

- yaml/buddy-error-codes.yaml
> Adjust homing calibration errors

- yaml/buddy-error-codes.yaml
> Add missing sheet error to MK4

- yaml/buddy-error-codes.yaml
BFW-6988
Better name and shorter title (last one did not fit).
> Rewrite warning (Loading obstruction)

- yaml/buddy-error-codes.yaml
> Approve XX118 + XX119 + XX324

- yaml/buddy-error-codes.yaml
> [PEC] Tweak precise homing errors

- yaml/buddy-error-codes.yaml
> Add blue errors from the firmware (error screen unification)

- yaml/buddy-error-codes.yaml
> Add iX to NOZZLE_CLEANING_FAILED_AUTORETRACT_ENABLE_ASK
