prusa3d/Prusa-Error-Codes

- prusaerrors/shared/codes.py
Touch-ui used old repo on gitlab. Export to enum was needed for touch-ui
> sl1: add dump to cpp enum

- .github/workflows/tests.yml
- 10_SL1/errors.yaml
- MANIFEST.in
- prusaerrors/shared/codes.py
- prusaerrors/sl1/codes.py
- prusaerrors/sl1/errors.yaml
- setup.py
- tests/test_exports.py
- Create `Sl1Codes` class content by decorator. This should be compatible
with direct declaration in codes.py. Only difference is that pyyaml is
required at runtime of Python users and compile time of `QML/C++/others`
dump users.
- Add yaml export support
- Test of integration: https://gitlab.com/prusa3d/sl1/meta-sl1/-/merge_requests/295
> SL1 source codes in YAML

- 10_SL1/errors.yaml
This error is used currently only in web UI when one-click should be shown but printer is not ready to print. In this case wizard is started so user cannot start a print from web UI. This is better description recommending to the user to check the printer physically and finish the wizard.
> NOT_AVAILABLE_IN_STATE(10506): text update

- 10_SL1/errors.yaml
- error which pops up when user replaces exposure screen which already has been in the printer previously
> OLD_EXPO_PANEL(10548): new code

- 04_MMU/errors_list.h
Makes interaction with Buddy FW easier.
Previously, this part of error definitions was drafted without any real knowledge how it may be used in the FW. This is now getting into shape, so time to finalize the data structures even for the buttons/operations in the error dialogs.
> Introduce MMU ErrDesc Button/Operation enum

- 10_SL1/errors.yaml
- prusaerrors/shared/codes.py
- prusaerrors/sl1/codes.py
- Minor fixes
- Fan, temp devices identified by mapped integers instead of direct translated strings. This is achieved by introducing new error codes that serve the same purpose as the old ones. Old ones are marked as deprecated. This solution was chosen to avoid possible errors and overall hassle with versioning, backward compatibility and translations.
- New error codes are improved in terms of parameter structure and availability of range limits.
> Numeric device ids

- 12_MINI/errors_list.h
These changes were made in the subrepo in Prusa-Firmware-Buddy.
They can be viewed with:
```bash
git subrepo branch --force lib/Prusa-Error-Codes
git log subrepo/lib/Prusa-Error-Codes
```
However, they have a wrong parent. `git-subrepo` seems to be messed up in some way I wasn't able to figure out. These commits are extracted from that branch and rebased on current master. After this is merged (barring something less forceful won't get us into a consistent state) the plan is to probably do a `git subrepo clone --force ...` which I've tested will make things right again.
> Update with changes made in Prusa-Firmware-Buddy

- 04_MMU/error-codes.yaml
minor MMU error codes adjustments: 
- deleted non relevant comment at FSENSOR TOO EARLY
- shorter text for SELECTOR CANNOT MOVE and IDLER CANNOT MOVE
- refined text for UNLOAD MANUALLY as this error isn't related to FINDA sensor exclusively.
> Add MMU err. 108 LOAD_TO_EXTRUDER_FAILED

- generate_buddy_headers.py
Adds two missing error categories and support for line breaks in error texts.
> generate_buddy_headers.py: Add support for bootloader errors

- 10_SL1/errors.yaml
The error will be shown when any of the firmware D-Bus services, that are expected to always be available, unregisters from the bus - indicating that it probably crashed.
Part of: SL1SW-544
> Add SYSTEM_SERVICE_CRASHED error to indicate crashed D-Bus services

- 04_MMU/error-codes.yaml
Please note LOAD_TO_EXTRUDER_FAILED is not an MMU error and therefore it behaves a bit differently. It must NOT contain a Retry button, otherwise unlimited retries will be issued.
BFW-3874
> Replace "Retry" for "Continue" in LOAD_TO_EXTRUDER_FAILED

- 04_MMU/error-codes.yaml
- Update titles to 20 chars max. Not only on MK3 lcd issue also on MK4
- All actions divided by `,` only. Spaces deleted.
- Consistent format makes it easier to script around these codes
- Change `ERR_ELECTRICAL_MCU_UNDERVOLTAGE_VCC` to `MCU_UNDERVOLTAGE_VCC` as it is already declared as Electrical issue
```
```
Counterpart for the Prusa-Firmware https://github.com/prusa3d/Prusa-Firmware/pull/4238
> Fix few issues

- 04_MMU/error-codes.yaml
- generate_buddy_headers.py
The type is meant to distinguish actual errors from warnings regular workflow dialogs.
The default `type` (if not specified) is `ERROR`, is that correct @JakoobCZ ?
> Add type to MMU errors

- 12_MINI/error-codes.yaml
- 13_MK4/error-codes.yaml
- 16_iX/error-codes.yaml
- 17_XL/error-codes.yaml
- 20_MK3.5/error-codes.yaml
General error is a error fallback in case of unrecognised error number.
HW version error is not used in bootloader (was in the past), but the implementation is prepared.
> Add unused but implemented errors

- 20_MK3.5/error-codes.yaml
In the last PR, I forgot to add this error to MK3.5 as well.
> Add MCU_MAXTEMP_ERR to MK3.5

- yaml/buddy-error-codes.yaml
Part of migrating the `error` bit field in marlin server to generalized FSM handling (which allows sending them to Connect).
> Add Connect warnings for further issues

- yaml/buddy-error-codes.yaml
Text of warning before accepting new Wi-Fi credentials.
BFW-5398
> Warning before accepting Wifi creds from NFC

- yaml/buddy-error-codes.yaml
This error was in the bootloader code since Mk3.5, but missing in the PEC
> Add missing XX615 error

- yaml/buddy-error-codes.yaml
Remove `Nozzle Cleaning failed` error from mk3.5, because it doesn't have loadcell.
> Remove MK3.5 inaccessible error

- tests/test_verify_buddy_errors_content.py
- yaml/buddy-error-codes.yaml
Added missing (replaced empty) titles. Check the commits for more info.
Also I have added a simple test that verifies the provided data (I know that most of the errors would be caught when generating the c++ code in our repo, but we can now check the values too (at least their length)).
BFW-5773
> Add missing titles

- README.md
- prusaerrors/shared/codes.py
- prusaerrors/sl1/__init__.py
- prusaerrors/sl1/codes.py
- prusaerrors/sl1/errors.yaml
- tests/test_sl1.py
- yaml/sla-error-codes.yaml
- yaml file moved to common `yaml` forlder
- all prefixes changed to XX and compatible printers set to both SL1 and M1 models
> SL1SW-2381: sla: select printer prefix according to detected model

- yaml/buddy-error-codes.yaml
Since the printer can't distinguished why it wants a new filament (at the point when this is reported), we make the text more general (it could be because the print instructions contain a gcode to change it, it could be stuck, ...)
BFW-6043.
> connect: More generic runout text

- yaml/buddy-error-codes.yaml
... and can therefore timeout during loading assistance
> Add XL to printers that have "loading tube"

- yaml/buddy-error-codes.yaml
The error text for GCODE_CROPPED recently popped up on my MK4S. The wording felt a little off, and this felt like a typo snuck in. 
> "As a result, it might have beet not executed correctly."
is now phrased as
> "As a result, it might not be executed correctly."
> Fix typo "beet" in GCODE_CROPPED

- yaml/buddy-error-codes.yaml
Changing warnings Chamber Overheating & Chamber Temperature Is Critical to be available also for XL
BFW-6242
> Chamber Temperature Warnings for XL as well

- yaml/buddy-error-codes.yaml
BFW-6728
XL also has chamber api which means it needs to have this warning accessible.
> Add XL to open/close vents warning printers

- yaml/buddy-error-codes.yaml
This reverts commit 6a6f04907ced20cb10da9923c83726ac2c028842.
If XL will be eligable for reporting mintemp / maxtemp errors, it should get a different error text.
> Revert "Add XL to chamber temp errors"

- yaml/buddy-error-codes.yaml
> Add MMU changes warning
